package DynamicAppDemo::Controller::FakeExample;
use Moose;
use namespace::clean -except => 'meta'; # N.B. namespace clean cest tres important
                                        #      as this package is introspected, a lot!

BEGIN { extends 'DynamicAppDemo::ControllerBase' }

# This is a fake controller.

# It exists to show an example of using ::ControllerBase which is autogenerated,
# which helps me seperate the building and testing of the controller action
# registration functionality, seperate the the code generation :)

sub register_me { 
    my ($self, $c) = @_;
    $c->res->body('quux');
    $c->res->header('X-Foo', 'bar');
}

sub _do_not_register_me { }

# In a non-trivial example, you would use MX::Method::Sigs :)

__PACKAGE__->meta->make_immutable;

